//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UiModule.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UiModule.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boards Quantity.
        /// </summary>
        public static string BoardsQuantity {
            get {
                return ResourceManager.GetString("BoardsQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board Thickness.
        /// </summary>
        public static string BoardThickness {
            get {
                return ResourceManager.GetString("BoardThickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both Sides.
        /// </summary>
        public static string BothSides {
            get {
                return ResourceManager.GetString("BothSides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Side.
        /// </summary>
        public static string BottomSide {
            get {
                return ResourceManager.GetString("BottomSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class 2.
        /// </summary>
        public static string Class2 {
            get {
                return ResourceManager.GetString("Class2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class 3.
        /// </summary>
        public static string Class3 {
            get {
                return ResourceManager.GetString("Class3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean.
        /// </summary>
        public static string Clean {
            get {
                return ResourceManager.GetString("Clean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controlled Impedance.
        /// </summary>
        public static string ControlledImpedance {
            get {
                return ResourceManager.GetString("ControlledImpedance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cooper Weight on Inner Layers.
        /// </summary>
        public static string CooperWeightOnInnerLayers {
            get {
                return ResourceManager.GetString("CooperWeightOnInnerLayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cooper Weight on Outer Layers.
        /// </summary>
        public static string CooperWeightOnOuterLayers {
            get {
                return ResourceManager.GetString("CooperWeightOnOuterLayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Impact.
        /// </summary>
        public static string CostImpact {
            get {
                return ResourceManager.GetString("CostImpact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d.
        /// </summary>
        public static string DaysShort {
            get {
                return ResourceManager.GetString("DaysShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flux Type.
        /// </summary>
        public static string FluxType {
            get {
                return ResourceManager.GetString("FluxType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important Board Preferences.
        /// </summary>
        public static string ImportantBoardPreferences {
            get {
                return ResourceManager.GetString("ImportantBoardPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPC Class.
        /// </summary>
        public static string IpcClass {
            get {
                return ResourceManager.GetString("IpcClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ITAR.
        /// </summary>
        public static string ITAR {
            get {
                return ResourceManager.GetString("ITAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead Free.
        /// </summary>
        public static string LeadFree {
            get {
                return ResourceManager.GetString("LeadFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material.
        /// </summary>
        public static string Material {
            get {
                return ResourceManager.GetString("Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Clean.
        /// </summary>
        public static string NoClean {
            get {
                return ResourceManager.GetString("NoClean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter.
        /// </summary>
        public static string Parameter {
            get {
                return ResourceManager.GetString("Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        public static string Preferences {
            get {
                return ResourceManager.GetString("Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences on this page supersede design file notes.
        /// </summary>
        public static string PreferencesOnThePageSupersedeDesignFileNotes {
            get {
                return ResourceManager.GetString("PreferencesOnThePageSupersedeDesignFileNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Basics.
        /// </summary>
        public static string ProjectBasics {
            get {
                return ResourceManager.GetString("ProjectBasics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Name.
        /// </summary>
        public static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote.
        /// </summary>
        public static string Quote {
            get {
                return ResourceManager.GetString("Quote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running Total.
        /// </summary>
        public static string RunningTotal {
            get {
                return ResourceManager.GetString("RunningTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See Notes.
        /// </summary>
        public static string SeeNotes {
            get {
                return ResourceManager.GetString("SeeNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silkscreen Color.
        /// </summary>
        public static string SilkscreenColor {
            get {
                return ResourceManager.GetString("SilkscreenColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solder Mask Color.
        /// </summary>
        public static string SolderMaskColor {
            get {
                return ResourceManager.GetString("SolderMaskColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Board Preferences.
        /// </summary>
        public static string SpecialBoardPreferences {
            get {
                return ResourceManager.GetString("SpecialBoardPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stackup.
        /// </summary>
        public static string Stackup {
            get {
                return ResourceManager.GetString("Stackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        public static string Standard {
            get {
                return ResourceManager.GetString("Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface Finish.
        /// </summary>
        public static string SurfaceFinish {
            get {
                return ResourceManager.GetString("SurfaceFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenting for Vias.
        /// </summary>
        public static string TentingForVias {
            get {
                return ResourceManager.GetString("TentingForVias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Impact.
        /// </summary>
        public static string TimeImpact {
            get {
                return ResourceManager.GetString("TimeImpact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Side.
        /// </summary>
        public static string TopSide {
            get {
                return ResourceManager.GetString("TopSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zipcode.
        /// </summary>
        public static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
    }
}
